spring:
  kafka:
    streams:
      application-id: kafka-streams-app
      properties:
        "default.key.serde": org.apache.kafka.common.serialization.Serdes$IntegerSerde
        "default.value.serde": org.apache.kafka.common.serialization.Serdes$StringSerde
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
    consumer:
      group-id: kafka-streams-app
    template:
      default-topic: topic1
    bootstrap-servers: localhost:9092
  application:
    name: kafka-streams-app
logging:
  level:
    root: info
    org.apache.kafka: warn
